export const INCREASE_PRICE = 'ADD_PRICE' 
export const DECREASE_PRICE  = 'DECREASE_PRICE'
export const CLEAR_PRICE = 'CLEAR_PRICE'
export const FETCH_PRICES = 'FETCH_PRICES';
export const FETCH_PRICES_SUCCESS = 'FETCH_PRICES_SUCCESS';
export const FETCH_PRICES_FAIL = 'FETCH_PRICES_FAIL';
export const UPDATE_PRICES = 'UPDATE_PRICES';
export const UPDATE_TOTAL_PRICE = 'UPDATE_TOTAL_PRICE';