export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const UPDATE_ORDERS = 'UPDATE_ORDERS';