export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS";
export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_FAIL = "FETCH_INGREDIENTS_FAIL";
